name: MADE_EX
channels:
  - defaults
dependencies:
  # project requirements from https://github.com/jvalue/made-exercise-feedback/blob/main/requirements.txt
  # own dependencies
    - python=3.11.5
    - nodejs
    - jupyter
    - pip
    - pip:
        - attrs==22.2.0
        - greenlet==2.0.2
        - iniconfig==2.0.0
        - numpy==1.24.2
        - packaging==23.0
        - pandas==1.5.3
        - pluggy==1.0.0
        - python-dateutil==2.8.2
        - pytz==2022.7.1
        - six==1.16.0
        - SQLAlchemy==1.4.46
        - typing_extensions==4.5.0
    #   - tensorflow